package io.github.sagaraggarwal86.jmeter.bpm.cli;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for CliArgs parsing and validation.
 */
@DisplayName("CliArgs")
class CliArgsTest {

    @TempDir
    Path tempDir;

    private Path createTempFile(String name) throws IOException {
        return Files.createFile(tempDir.resolve(name));
    }

    // ── Help ─────────────────────────────────────────────────────────────────

    @Test
    @DisplayName("--help sets help flag and skips validation")
    void help_setsFlag() {
        CliArgs cli = CliArgs.parse(new String[]{"--help"});
        assertTrue(cli.help());
        assertTrue(cli.errors().isEmpty(), "Help should skip validation");
    }

    @Test
    @DisplayName("-h is alias for --help")
    void shortHelp() {
        assertTrue(CliArgs.parse(new String[]{"-h"}).help());
    }

    // ── Required args ────────────────────────────────────────────────────────

    @Test
    @DisplayName("--output sets output file")
    void outputFile() throws IOException {
        Path f = createTempFile("in.jsonl");
        CliArgs cli = CliArgs.parse(new String[]{"-i", f.toString(), "-o", "report.html"});
        assertEquals(Path.of("report.html"), cli.outputFile());
    }

    // ── Optional args ────────────────────────────────────────────────────────

    @Test
    @DisplayName("Default output is null (auto-generated by pipeline)")
    void defaultOutput() throws IOException {
        Path f = createTempFile("in.jsonl");
        CliArgs cli = CliArgs.parse(new String[]{"-i", f.toString()});
        assertNull(cli.outputFile());
    }

    @Test
    @DisplayName("Unknown long flag is rejected")
    void unknownLongFlag_rejected() throws IOException {
        Path f = createTempFile("in.jsonl");
        CliArgs cli = CliArgs.parse(new String[]{"-i", f.toString(), "--bogus-flag", "value"});
        assertTrue(cli.errors().stream().anyMatch(e -> e.contains("Unknown")));
    }

    @Test
    @DisplayName("--virtual-users parsed as int")
    void virtualUsers() throws IOException {
        Path f = createTempFile("in.jsonl");
        CliArgs cli = CliArgs.parse(new String[]{"-i", f.toString(), "--virtual-users", "50"});
        assertEquals(50, cli.virtualUsers());
    }

    @Test
    @DisplayName("Non-integer --virtual-users produces error")
    void virtualUsersNonInt() throws IOException {
        Path f = createTempFile("in.jsonl");
        CliArgs cli = CliArgs.parse(new String[]{"-i", f.toString(), "--virtual-users", "abc"});
        assertTrue(cli.errors().stream().anyMatch(e -> e.contains("integer")));
    }

    @Test
    @DisplayName("--search --regex --exclude all parsed correctly")
    void filterFlags() throws IOException {
        Path f = createTempFile("in.jsonl");
        CliArgs cli = CliArgs.parse(new String[]{
                "-i", f.toString(), "--search", "Login.*", "--regex", "--exclude"});
        assertEquals("Login.*", cli.search());
        assertTrue(cli.regex());
        assertTrue(cli.exclude());
    }

    // ── Filter flags ─────────────────────────────────────────────────────────

    @Test
    @DisplayName("Invalid regex with --regex produces validation error")
    void invalidRegex_error() throws IOException {
        Path f = createTempFile("in.jsonl");
        CliArgs cli = CliArgs.parse(new String[]{
                "-i", f.toString(), "--search", "[invalid", "--regex"});
        assertTrue(cli.errors().stream().anyMatch(e -> e.contains("regex")));
    }

    @Test
    @DisplayName("Unknown argument produces error")
    void unknownArg() throws IOException {
        Path f = createTempFile("in.jsonl");
        CliArgs cli = CliArgs.parse(new String[]{"-i", f.toString(), "--bogus"});
        assertTrue(cli.errors().stream().anyMatch(e -> e.contains("Unknown")));
    }

    // ── Unknown args ─────────────────────────────────────────────────────────

    @Test
    @DisplayName("Flag without value produces error")
    void missingValue() {
        CliArgs cli = CliArgs.parse(new String[]{"-i"});
        assertTrue(cli.errors().stream().anyMatch(e -> e.contains("requires a value")));
    }

    // ── Missing value ────────────────────────────────────────────────────────

    @Test
    @DisplayName("--scenario-name and --description parsed correctly")
    void metadata() throws IOException {
        Path f = createTempFile("in.jsonl");
        CliArgs cli = CliArgs.parse(new String[]{
                "-i", f.toString(),
                "--scenario-name", "Sprint 42",
                "--description", "Peak load"});
        assertEquals("Sprint 42", cli.scenarioName());
        assertEquals("Peak load", cli.description());
    }

    // ── Metadata ─────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("Input file validation")
    class InputValidation {

        @Test
        @DisplayName("Missing --input produces error")
        void missingInput_error() {
            CliArgs cli = CliArgs.parse(new String[]{});
            assertFalse(cli.errors().isEmpty());
            assertTrue(cli.errors().get(0).contains("--input"));
        }

        @Test
        @DisplayName("Non-existent --input file produces error")
        void nonExistentInput_error() {
            CliArgs cli = CliArgs.parse(new String[]{"-i", "/nonexistent/file.jsonl"});
            assertFalse(cli.errors().isEmpty());
        }

        @Test
        @DisplayName("Valid --input file produces no errors")
        void validInput_noErrors() throws IOException {
            Path f = createTempFile("test.jsonl");
            CliArgs cli = CliArgs.parse(new String[]{"-i", f.toString()});
            assertTrue(cli.errors().isEmpty());
            assertEquals(f, cli.inputFile());
        }
    }
}
